docker_image: "jpetazzo/dind"
services:
- docker
setup:
- "curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
- "chmod +x /usr/local/bin/docker-compose"
dependencies:
- "docker-compose up"
test:
- "docker-compose run app echo Tests"
